# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MBER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MBER
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'RxCoreLocation'

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'GeoFire'

  pod 'SDWebImage'
  pod 'JGProgressHUD'
end
